/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RouterHistory } from "@stencil/router";
export namespace Components {
	interface AppEditor {
		source: Uint8Array;
	}
	interface AppRoot {}
	interface FileLoadMethod {
		history: RouterHistory;
		onFileInput: (e: Event) => void;
	}
}
declare global {
	interface HTMLAppEditorElement
		extends Components.AppEditor,
			HTMLStencilElement {}
	var HTMLAppEditorElement: {
		prototype: HTMLAppEditorElement;
		new (): HTMLAppEditorElement;
	};
	interface HTMLAppRootElement
		extends Components.AppRoot,
			HTMLStencilElement {}
	var HTMLAppRootElement: {
		prototype: HTMLAppRootElement;
		new (): HTMLAppRootElement;
	};
	interface HTMLFileLoadMethodElement
		extends Components.FileLoadMethod,
			HTMLStencilElement {}
	var HTMLFileLoadMethodElement: {
		prototype: HTMLFileLoadMethodElement;
		new (): HTMLFileLoadMethodElement;
	};
	interface HTMLElementTagNameMap {
		"app-editor": HTMLAppEditorElement;
		"app-root": HTMLAppRootElement;
		"file-load-method": HTMLFileLoadMethodElement;
	}
}
declare namespace LocalJSX {
	interface AppEditor {
		source?: Uint8Array;
	}
	interface AppRoot {}
	interface FileLoadMethod {
		history?: RouterHistory;
		onFileInput?: (e: Event) => void;
	}
	interface IntrinsicElements {
		"app-editor": AppEditor;
		"app-root": AppRoot;
		"file-load-method": FileLoadMethod;
	}
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
	export namespace JSX {
		interface IntrinsicElements {
			"app-editor": LocalJSX.AppEditor &
				JSXBase.HTMLAttributes<HTMLAppEditorElement>;
			"app-root": LocalJSX.AppRoot &
				JSXBase.HTMLAttributes<HTMLAppRootElement>;
			"file-load-method": LocalJSX.FileLoadMethod &
				JSXBase.HTMLAttributes<HTMLFileLoadMethodElement>;
		}
	}
}
