/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RouterHistory } from "@stencil/router";
export namespace Components {
	interface AppEditor {
		fileSource: Uint8Array;
		history: RouterHistory;
	}
	interface AppRoot {}
	interface AppWelcome {
		history: RouterHistory;
	}
	interface FileLoadMethod {
		history: RouterHistory;
	}
}
declare global {
	interface HTMLAppEditorElement
		extends Components.AppEditor,
			HTMLStencilElement {}
	var HTMLAppEditorElement: {
		prototype: HTMLAppEditorElement;
		new (): HTMLAppEditorElement;
	};
	interface HTMLAppRootElement
		extends Components.AppRoot,
			HTMLStencilElement {}
	var HTMLAppRootElement: {
		prototype: HTMLAppRootElement;
		new (): HTMLAppRootElement;
	};
	interface HTMLAppWelcomeElement
		extends Components.AppWelcome,
			HTMLStencilElement {}
	var HTMLAppWelcomeElement: {
		prototype: HTMLAppWelcomeElement;
		new (): HTMLAppWelcomeElement;
	};
	interface HTMLFileLoadMethodElement
		extends Components.FileLoadMethod,
			HTMLStencilElement {}
	var HTMLFileLoadMethodElement: {
		prototype: HTMLFileLoadMethodElement;
		new (): HTMLFileLoadMethodElement;
	};
	interface HTMLElementTagNameMap {
		"app-editor": HTMLAppEditorElement;
		"app-root": HTMLAppRootElement;
		"app-welcome": HTMLAppWelcomeElement;
		"file-load-method": HTMLFileLoadMethodElement;
	}
}
declare namespace LocalJSX {
	interface AppEditor {
		fileSource?: Uint8Array;
		history?: RouterHistory;
	}
	interface AppRoot {}
	interface AppWelcome {
		history?: RouterHistory;
	}
	interface FileLoadMethod {
		history?: RouterHistory;
	}
	interface IntrinsicElements {
		"app-editor": AppEditor;
		"app-root": AppRoot;
		"app-welcome": AppWelcome;
		"file-load-method": FileLoadMethod;
	}
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
	export namespace JSX {
		interface IntrinsicElements {
			"app-editor": LocalJSX.AppEditor &
				JSXBase.HTMLAttributes<HTMLAppEditorElement>;
			"app-root": LocalJSX.AppRoot &
				JSXBase.HTMLAttributes<HTMLAppRootElement>;
			"app-welcome": LocalJSX.AppWelcome &
				JSXBase.HTMLAttributes<HTMLAppWelcomeElement>;
			"file-load-method": LocalJSX.FileLoadMethod &
				JSXBase.HTMLAttributes<HTMLFileLoadMethodElement>;
		}
	}
}
